ued123/modeling

README.md, build.gradle, docker-compose.yml, init_data_mongo/collection_drink_init_data.json, src/main/java/com.example/config/AppConfig.java, src/test/java/com/example/config/AppConfigTest.java
> - mongodb docker-compose.yml 작성
> - 더미데이터 init data json 작성
> - mongoTemplate, mongoClient 수동 빈 등록
> - test코드 작성. 현재는 커넥션 연결 상태만 확인. startSession
@skydrive888
=> ### 몽고디비 연동

build.gradle, cash-api/src/main/java/com/example/mongo/model/Transaction.java, cash-api/src/main/java/com/example/mongo/model/TransactionType.java, cash-api/src/main/java/com/example/transaction/repo/TransactionRepository.java, cash-api/src/test/groovy/TestApplication.groovy, cash-api/src/test/groovy/com/example/transaction/repo/TransactionRepositoryTest.groovy, cash-api/src/test/groovy/mongo/DbIntegrationTest.groovy
- Transaction 도메인 생성
- Spock 기반 테스트 케이스 작성
- test 패키지 밑에 groovy 패키지를 기준으로 정한다.
- 클래스 파일은 xxx.groovy 이다
- sample: TransactionRepositoryTest.groovy
=> 거래 내역 도메인 추가

build.gradle, cash-api/src/main/java/com/example/mongo/model/Transaction.java, cash-api/src/main/java/com/example/transaction/service/TransactionService.java, cash-api/src/main/java/com/example/transaction/service/TransactionServiceImpl.java, cash-api/src/test/groovy/com/example/transaction/fixture/TransactionFixtureBuilder.groovy, cash-api/src/test/groovy/com/example/transaction/service/TransactionServiceTest.groovy
- org.springframework.boot:spring-boot-starter-validation 추가
- Transaction 유효성 검사 추가
- 입금 거래 내역 생성 로직 추가
- DSL 기반 TrasnactionBuilder.groovy 추가
- 입금 거래 내역 테스트 코드 추가
=> 입금 거래 내역 생성 로직 추가

build.gradle, cash-api/src/main/java/com/example/ExceptionTranslator.java, cash-api/src/main/java/com/example/cash/controller/CashController.java, cash-api/src/main/java/com/example/cash/dto/CashDepositPayLoad.java, cash-api/src/main/java/com/example/error/ErrorBody.java, cash-api/src/main/java/com/example/error/ErrorMessage.java, cash-api/src/main/java/com/example/error/SimpleFieldError.java, cash-api/src/test/kotlin/com/example/cash/controller/CashControllerTest.kt
- 유효성 검사 실패시 에러 응답 생성 로직 추가
- 입금 하기 api requestBody 필드 값이 유효하지 않으면 에러 응답 발생
=> 유효성 검사 실패시 에러 처리 로직 추가

cash-api/src/main/java/com/example/cash/repo/CashRepository.java, cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/main/java/com/example/mongo/model/Cash.java, cash-api/src/test/kotlin/com/example/cash/repo/CashRepositoryTest.kt, cash-api/src/test/kotlin/com/example/cash/service/CashServiceTest.kt
- Optional 위주로 리팩토링 (Service, Repository, Entity)
- 테스트 코드 수정
- CashServiceTest 테스트 케이스 추가 필요 `cash 데이터가 없는 경우`
=> 입금하기 로직 수정

application/build.gradle, cash-api/src/main/java/com/example/mongo/config/MongoInitCashDataRunner.java, drink-api/src/main/java/com/example/mongo/config/MongoInitDrinkDisplayDataRunner.java
초기화 이후 금액 입금 deposit api 테스트시 잘 되었습니다.
=> [#88] cash 데이터 초기화 로직 추가

cash-api/src/main/java/com/example/ExceptionTranslator.java, cash-api/src/main/java/com/example/error/ErrorBody.java, cash-api/src/test/kotlin/com/example/cash/controller/CashControllerTest.kt
500 server internal error postman test
=> [#101] 정의하지 않은 예외 발생시 에러 처리 fix

cash-api/src/main/java/com/example/ExceptionTranslator.java, cash-api/src/main/java/com/example/cash/controller/CashController.java, cash-api/src/main/java/com/example/cash/dto/CashChangeView.java, cash-api/src/main/java/com/example/cash/service/CashService.java, cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/main/java/com/example/error/ErrorBody.java, cash-api/src/main/java/com/example/error/ErrorMessage.java, cash-api/src/main/java/com/example/error/exception/CashEmptyException.java, cash-api/src/test/kotlin/com/example/cash/controller/CashControllerTest.kt
우선 거스름돈 api 정의하고 테스트 코드 작성하였습니다.
1. Cash가 0원일때 발생시킬 CashEmptyException 커스텀 에러를 생성, handler추가, Error 메시지 추가
2. controller에 거스름돈 api 추가, 테스트 코드 200,404,500 케이스 테스트
3. service단은 인터페이스만 생성 하였음
=> [#109] cash 거스름돈 controller 구현

cash-api/src/main/java/com/example/mongo/model/Transaction.java, cash-api/src/main/java/com/example/mongo/model/TransactionType.java, cash-api/src/main/java/com/example/transaction/service/TransactionService.java, cash-api/src/main/java/com/example/transaction/service/TransactionServiceImpl.java, cash-api/src/test/kotlin/com/example/transaction/service/TransactionServiceTest.kt
- 거스름돈에 대한 transaction(거래이력) service 추가
- 변수를 활용한 테스트코드
=> [#112] 거스름돈에 대한 transaction(거래이력) service 추가

cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/main/java/com/example/error/exception/CashEmptyException.java, cash-api/src/main/java/com/example/mongo/model/Cash.java, cash-api/src/test/kotlin/com/example/cash/controller/CashControllerTest.kt, cash-api/src/test/kotlin/com/example/cash/service/CashServiceTest.kt
- #115 PR에 대한 소스 리뷰
- 리뷰 보시고 의견 주시면 감사하겠습니다. 🙏 
- CashEmptyException 객체 생성시, default status 404로 선언
- 현재 도메인은 immutable pattern 을 준수하기 때문에, 
필드 변수 수정이 필요한 경우, 반드시 객체를 복사후에 처리 하는것을 추천드립니다.
- 해당 도메인에서 처리가 필요한 View 객체는, Entity 관리 클래스에서 변환 로직을 생성하는걸 추천드립니다.
- Annotation: MongoId, CreatedDate, LastModifiedDate 는 데이터 베이스 저장전에 생성되기 때문에, 
객체 생성로직에 필요하지 않습니다.
- 거스름돈 반환 처리 과정 수정
- CashEmptyException 는 Client - Server간 에러 발생을 정의한 예외이기 때문에, 
Entity Layer에서 사용하는건 추천하지 않습니다.
[Controller-Service-Repository Exception Handling-1](https://itecnotes.com/software/design-where-would-you-handle-exceptions-controller-service-repository/)
[Controller-Service-Repository Exception Handling-2](https://vaadin.com/blog/ddd-part-3-domain-driven-design-and-the-hexagonal-architecture)
- kotlin 에서는 `;` 사용하지 않으셔도 됩니다. …
=>  review: cash 거스름돈 service 구현

cash-api/src/main/java/com/example/cash/controller/CashController.java, cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/main/java/com/example/error/exception/CashEmptyException.java, cash-api/src/main/java/com/example/mongo/model/Cash.java, cash-api/src/test/kotlin/com/example/cash/controller/CashControllerTest.kt, cash-api/src/test/kotlin/com/example/cash/service/CashServiceTest.kt
캐시 거스름돈 api 서비스단 개발, 테스트 코드 추가, controller 정책 수정
- 잔액이 없을때 
- 200 일때 (잔액 1000원)
=> [#110] cash 거스름돈 service 구현

cash-api/src/main/java/com/example/cash/service/CashService.java, cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/main/java/com/example/error/ErrorMessage.java, cash-api/src/main/java/com/example/error/exception/CashNotEnoughException.java, cash-api/src/main/java/com/example/mongo/model/Cash.java, cash-api/src/main/java/com/example/mongo/model/Transaction.java, cash-api/src/main/java/com/example/mongo/model/TransactionType.java, cash-api/src/main/java/com/example/transaction/service/TransactionService.java, cash-api/src/main/java/com/example/transaction/service/TransactionServiceImpl.java, cash-api/src/test/kotlin/com/example/cash/service/CashServiceTest.kt, cash-api/src/test/kotlin/com/example/transaction/service/TransactionServiceTest.kt
- 입금하기 로직 수정
- 입금 금액 사용 로직 추가
- 입금 금액 사용 내역 작성 로직 추가
=> [#119][#128] 입금 금액 사용 로직 추가 & 입금하기 로직 수정

purchase-api/build.gradle, purchase-api/src/main/java/com/example/mongo/config/MongoConfigurer.java, purchase-api/src/main/java/com/example/openapi/OpenApiConfig.java, purchase-api/src/test/kotlin/com/example/TestApplication.kt, purchase-api/src/test/kotlin/com/example/config/DbExtension.kt, purchase-api/src/test/kotlin/com/example/config/KotestProjectConfig.kt, settings.gradle
구매(purchase) 도메인 프로젝트 init
- gradle 설정
- kotest 설정
- mongodb 설정
- openapi 설정
=> [#123] purchase-api 프로젝트 init

application/build.gradle, purchase-api/src/main/java/com/example/purchase/controller/PurchaseController.java, purchase-api/src/main/java/com/example/purchase/dto/PurchaseDrinkPayLoad.java, purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java, purchase-api/src/main/java/com/example/purchase/service/PurchaseServiceImpl.java, purchase-api/src/test/kotlin/com/example/purchase/controller/PurchaseControllerTest.kt
1. ResponseEntity 활용. 헤더 값만 응답 할 수 있도록 정의함.
2. 컨트롤러 kotest 작성(validation error, server error ,204 정상케이스)
=> [#131] 음료수 구매 rest controller 생성

purchase-api/src/main/java/com/example/mongo/model/Order.java, purchase-api/src/main/java/com/example/order/repo/OrderRepository.java, purchase-api/src/test/kotlin/com/example/order/fixture/OrderBuilder.kt, purchase-api/src/test/kotlin/com/example/order/repo/OrderRepositoryTest.kt
자판기는 음료수 버튼을 눌렀을때 바로나오기 때문에 (수량에 대한 체크하는 부분이 없음)
QTY,amount,unitprice 개념은 중요하지 않을거같아서 주문서 생성에 필요한 최소 필드만을 가지고 일단 정의를 해봤습니다.
=> [#135][#136] 주문서(order) 도메인 생성 및 repo 구성

cash-api/src/main/java/com/example/mongo/model/entitymapper/CashMapper.java, cash-api/src/test/kotlin/com/example/cash/repo/CashRepositoryTest.kt
- cash 잔고 사용 로직 수정
- cash 잔고 입금 로직 수정
- https://stackoverflow.com/questions/56149509/mapstruct-use-of-context-in-source-argument-of-mapping
- https://mapstruct.org/documentation/stable/api/org/mapstruct/Context.html
=> review: cash, transaction entitymapper

cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/main/java/com/example/mongo/model/entitymapper/CashMapper.java, cash-api/src/test/kotlin/com/example/cash/service/CashServiceTest.kt, drink-api/src/main/java/com/example/display/controller/DisplayController.java, drink-api/src/main/java/com/example/display/service/DisplayService.java, drink-api/src/main/java/com/example/display/service/DisplayServiceImpl.java, drink-api/src/main/java/com/example/mongo/model/Display.java, drink-api/src/main/java/com/example/mongo/model/entitymapper/DisplayDrinkMapper.java, drink-api/src/test/kotlin/com/example/display/controller/DisplayControllerTest.kt, drink-api/src/test/kotlin/com/example/display/service/DisplayServiceTest.kt, drink-api/src/test/kotlin/com/example/drink/fixture/DrinkBuilder.kt, drink-api/src/test/kotlin/com/example/mongo/model/entitymapper/DisplayDrinkMapperTest.kt
1. entitymapper 도입, displayService를 활용하여 필터링 및 view 반환
2. entitymapper -> 음료수 가격이 변환되지 않아 price 변환 필드 추가
=> [#143] drink&display 도메인 entitymapper 적용

.gitignore, drink-api/src/main/java/com/example/drink/service/DrinkService.java, drink-api/src/main/java/com/example/drink/service/DrinkServiceImpl.java, drink-api/src/main/java/com/example/mongo/model/Drink.java, drink-api/src/main/java/com/example/mongo/model/entitymapper/DrinkMapper.java, drink-api/src/test/kotlin/com/example/drink/service/DrinkServiceImplTest.kt
- 음료수 조회 함수명 수정
- getDrinkByDrinkCode -> getByDrinkCode
- 품절 예외 케이스 제거 
- 음료수 꺼내기 로직 추가
- drinkMapper 추가
- 음료수 수량 감소시 객체 복사하여 처리
=> review: 음료수 가져오기 로직

.gitignore, drink-api/src/main/java/com/example/drink/repo/DrinkRepository.java, drink-api/src/main/java/com/example/drink/service/DrinkService.java, drink-api/src/main/java/com/example/drink/service/DrinkServiceImpl.java, drink-api/src/main/java/com/example/error/ErrorMessage.java, drink-api/src/main/java/com/example/error/exception/DrinkNotExistExcepion.java, drink-api/src/main/java/com/example/error/exception/DrinkSoldOutException.java, drink-api/src/main/java/com/example/mongo/model/Drink.java, drink-api/src/main/java/com/example/mongo/model/entitymapper/DrinkMapper.java, drink-api/src/test/kotlin/com/example/drink/service/DrinkServiceImplTest.kt
- drinkCode로 drink정보 조회
1. 음료수 정보 없을때, 음료수 수량 없을때 커스텀 에러 정의
2. optional `orElseThrow` 활용
3. kotest 서비스 테스트 코드 작성
=> [#148][drink] 음료수 가져오기 서비스 구현 

cash-api/src/main/java/com/example/cash/service/CashService.java, cash-api/src/main/java/com/example/cash/service/CashServiceImpl.java, cash-api/src/test/kotlin/com/example/cash/service/CashServiceTest.kt
- cash charge 사용시 사용금액에 대한 거래이력(transaction) 리턴으로 수정
=> [#151] cash 도메인 charge 메서드 리턴값 변경

purchase-api/build.gradle, purchase-api/src/main/java/com/example/mongo/model/entitymapper/OrderMapper.java, purchase-api/src/main/java/com/example/order/service/OrderService.java, purchase-api/src/main/java/com/example/order/service/OrderServiceImpl.java, purchase-api/src/main/java/com/example/purchase/controller/PurchaseController.java, purchase-api/src/main/java/com/example/purchase/service/PurchaseService.java, purchase-api/src/main/java/com/example/purchase/service/PurchaseServiceImpl.java, purchase-api/src/test/kotlin/com/example/mongo/model/entitymapper/OrderMapperTest.kt, purchase-api/src/test/kotlin/com/example/order/fixture/DrinkBuilder.kt, purchase-api/src/test/kotlin/com/example/order/fixture/TransactionBuilder.kt, purchase-api/src/test/kotlin/com/example/order/service/OrderServiceImplTest.kt, purchase-api/src/test/kotlin/com/example/purchase/controller/PurchaseControllerTest.kt
=> [#154] purchase service 구현(각 도메인 서비스 결합) 

cash-api/src/main/java/com/example/mongo/model/entitymapper/CashMapper.java
=> [#159] 금액 입금 api에 bug 
